name: Build and deploy Sphinx website

on:
  push:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install sphinx

      - name: Build Sphinx website 
        run: |
          sphinx-build -b html source build

      - name: Upload static website
        uses: actions/upload-pages-artifact
        with:
          path: build
